### ISSUE TITLE
Is there a release planned to include passing configurations as attributes?

### ISSUE THREAD

**Issue by seanpdoyle** [AgilionApps/ember-cli-input-mask#5]
The feature introduced in https://github.com/IcarusWorks/ember-cli-input-mask/commit/a0234b4f31d36f16c92a06221387c6990a2797fe that supports configuring the plugin based on the component's attributes.

Is that feature considered stable?

Will there be a version bump and NPM release soon?

**Comment by patrickberkeley** [comment]
We are going to archive this addon in favor of https://github.com/pzuraq/ember-inputmask.
